# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_user:
    registration:
        confirmation:
            enabled: false
    db_driver: orm
    user_class: App\Entity\User
    firewall_name: main
    service:                               # this lines
        mailer: fos_user.mailer.twig_swift # this lines
    from_email:
        address: "%env(resolve:FOS_MAILER_USER)%"
        sender_name: "%env(resolve:FOS_MAILER_USER)%"